package modelo.entidades;
// Generated 27 ene. 2021 10:46:18 by Hibernate Tools 5.2.12.Final

/**
 * Contactousuario generated by hbm2java
 */
public class Contactousuario implements java.io.Serializable {

	private ContactousuarioId id;
	private Usuario usuario;

	public Contactousuario() {
	}

	public Contactousuario(ContactousuarioId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public ContactousuarioId getId() {
		return this.id;
	}

	public void setId(ContactousuarioId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
