package modelo.entidades;
// Generated 27 ene. 2021 10:46:18 by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private int idAutor;
	private String nombre;
	private String apellidos;
	//private Set autorlibros = new HashSet(0);
	private List<Libro> libros = new ArrayList<Libro>();

	public Autor() {
	}

	public Autor(int idAutor, String nombre, String apellidos) {
		this.idAutor = idAutor;
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Autor(int idAutor, String nombre, String apellidos, List<Libro> libros) {
		this.idAutor = idAutor;
		this.nombre = nombre;
		this.apellidos = apellidos;
		//this.autorlibros = autorlibros;
		this.libros = libros;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

//	public Set getAutorlibros() {
//		return this.autorlibros;
//	}
//
//	public void setAutorlibros(Set autorlibros) {
//		this.autorlibros = autorlibros;
//	}
	public List<Libro> getLibros(){
		return libros;
	}
	public void setLibros(List<Libro> libros) {
		this.libros = libros;
	}
}
