package modelo.entidades;
// Generated 27 ene. 2021 10:46:18 by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.mysql.fabric.xmlrpc.base.Array;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private String codLibro;
	private String titulo;
	private String editorial;
	private float precio;
	private List<Autor> autores = new ArrayList<Autor>();
	private List<Ejemplar> ejemplares = new ArrayList<Ejemplar>();
	
	public Libro() {}	

	public Libro(String codLibro, String titulo, String editorial, float precio) {
		this.codLibro = codLibro;
		this.titulo = titulo;
		this.editorial = editorial;
		this.precio = precio;
	}

	public Libro(String codLibro, String titulo, String editorial, float precio,
			List<Autor> autores, List<Ejemplar> ejemplares) {
		this.codLibro = codLibro;
		this.titulo = titulo;
		this.editorial = editorial;
		this.precio = precio;
		this.autores = autores;
		this.ejemplares = ejemplares;
	}

	public String getCodLibro() {
		return this.codLibro;
	}

	public void setCodLibro(String codLibro) {
		this.codLibro = codLibro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

	public List<Autor> getAutores() {
		return autores;
	}

	public void setAutores(List<Autor> autores) {
		this.autores = autores;
	}

	public List<Ejemplar> getEjemplares() {
		return ejemplares;
	}

	public void setEjemplares(List<Ejemplar> ejemplares) {
		this.ejemplares = ejemplares;
	}

}
